### ISSUE TITLE
Release 0.3 - Discussion

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/nowdock-plasmoid#35] opened 2016-09-10 08:58 UTC
Hello, 

I am thinking the next days to release Now Dock plasmoid and panel (0.3) ... I believe the panel publishment will motivate more people!! (At least I hope so)

So I would like you opinion in the following:
1. There arent any "show stopper" bugs for this to happen based on your experience from their usement, do you agree?
2.  The current state of automatic icon resizement for the new user could be a little scary. Currently there is a state of **"Automatic"** for icon sizes which takes into account both height and length of the panel in order to not exist hidden items in it. And of course _(..32px, 48px, ...)_ that take into account only the length of the panel in order to shrink the icon size if needed... 
   My opinion is that when the user has set a direct size _(32px.. 48px..)_ at least for the current implementation this should **NOT** be changed  by the panel. Do you agree?
   _(I have to update this if you agree...)_
3. Most of the users are refering to **"Window Previews"**. Actually this is something I dont use but it would be also good to support your workflows. 

So for 0.3 versions I believe that when 2,3 are ready we are ready to launch...
What do you think?

**Comment by kupiqu** [comment] 2016-09-10 12:32
Perhaps you could decide what use case is going to be the main target for default behavior (maybe you did already).

For instance if the use case is a basic linux user, perhaps default behavior would consider to imitate the default plasma panel but with the nowdock panel and plasmoid (automatic icon size) instead, and with current theme modified for default transparency.

I recognize this is quite a change, would this make sense for you?

Window preview would be a very nice add in my opinion.

**Comment by psifidotos** [comment] 2016-09-10 13:25
> For instance if the use case is a basic linux user, perhaps default behavior would consider to imitate the default plasma panel but with the nowdock panel and plasmoid (automatic icon size) instead, 

imitate the default panel, you mean adding the same plasmoids in it?
so please can you mention the defaults you are proposing for the Now Dock Panel?
_zoom factor, showing background, icon size_
I think you are proposing,
 _1.0, no, automatic_ is that correct?

> and with current theme modified for default transparency.

this is not in my hand... can not do anything about it... it would be optimal to be able to present a panel with transparenty immediate after the Now Dock Panel is first installed, unfortunately this can not be done yet... Let's hope for Plasma 5.9

**Comment by psifidotos** [comment] 2016-09-10 13:26
> I recognize this is quite a change,

why? I dont see any radical, do I miss anything?

**Comment by kupiqu** [comment] 2016-09-10 16:28
I would actually suggest a scaling factor > 1, so nowdock shows all its power :) e.g. 1.5

I said it is quite a change for these 2 main reasons:
- install nowdock plasmoid inside nowdock panel together with the rest that is installed in a default panel in vanilla plasma 5 (basically exchanging the default task bar by the nowdock plasmoid). One would need to investigate what are the plasmoids that are added to a default panel in vanilla plasma 5...
- set the transparency by default under the hood (but this doesn't seem to be possible yet)

**Comment by psifidotos** [comment] 2016-09-10 17:41
> install nowdock plasmoid inside nowdock panel together with the rest that is installed in a default panel in vanilla plasma 5 (basically exchanging the default task bar by the nowdock plasmoid). One would need to investigate what are the plasmoids that are added to a default panel in vanilla plasma 5..

unfortunately in order to create a default layout for a panel an another piece of software is needed... I can not add in NowDock panel by default something... I have installed in my system a default layout but for the simple user this is more than difficult... these layouts do not have any easy way to install...

today I have another problem... I found a way to load svg icons and thus being able to support sizes in between for example 52, 58, 38 etc...

I tried to implement this also for the Now Dock panel but another problem arised... Even though icons in Now Dock plasmoid are shown with no issues, the plasmoids around them look out of place... :-( they cant support these sizes... 

I dont know what to do now... either support only the standard icon sizes even when the panel shrinks its content automatic because of sizes violation or leave it that way, tasks shown perfectly and the plasmoids around them smaller...
:(

![spectacle tj2636](https://cloud.githubusercontent.com/assets/2216474/18412443/eff083b4-7796-11e6-819c-8774f192cc07.png)

**Comment by kupiqu** [comment] 2016-09-10 17:59
Oh, that's unfortunate, I very much like the idea of using svg's for icons by default. It would be so great if plasma developers would consider adding that possibility all around in Plasma 5.9

**Comment by alexjp** [comment] 2016-09-10 18:02
Well, little late in the discussion, sorry.

Well, for me, plasmoid nowdock is ready to go. Does everything I need and does it well enough, now its only "improving things".

I don't really use nowdock panel, because it would need to support proper spacing like I have on the screenshot of "show us your docks". I am using a unity style configuration.

I don't really know if this is the place to say this, but if version 0.3 is going to live through plasma 5.8, I am noticing a problem with plasma master:
in main.qml, line 171:
         screen: plasmoid.screen
has a problem with plasma master, says screen is not available. ( I commented that line and plasmoid worked ).

To point 2, in keeping with plasma, it should resize its icons based on the size of the panel ( like taskmanager does ). But I see no problem in keeping like it is for now, until a proper working implementation. ( note, i am not talking about svg icons, but actually resize 32px -> 48px -> 64px depending on the panel size, like plasma taskmanager and other plasmoids do ).

As to point 3, I think it depends on what you plan to do in regards to a 0.4 version. If you plan a quick 0.3 and quick 0.4 version, I think there is no problem in missing window previews. If not, and you plan to make a 0.3 _almost lts_ version, then windows previews could be really handy, especially for multiple windows in same launcher handling.

I will test nowdock panel, because I mostly only use nowdock.

**Comment by alexjp** [comment] 2016-09-10 18:19
Actually, just tested nowdock panel, the automatic icon resizing seems great. Should go into nowdock plasmoid.

**Comment by kupiqu** [comment] 2016-09-10 18:46
I agree that nowdock is working great now and ready for 0.3 (agree also that windows preview could be 0.4 if it is done soon).

My main concern is that to get it in a nice setting for a naive user is difficult (panel vs plasmoid, which the user doesn't know much about;  grayed settings, which give the impression that something is missing or just wrong in the setup; etc.)

For instance, is there a reason why nowdock plasmoid is not just inside a nowdock panel by default? Whether one adds or not other plasmoids to the panel is then optional, isn't it? That could remove grayed things from the plasmoid and would avoid duplicating features in the plasmoid and panel.

Just a possibilty (perhaps I miss sth, and some people really prefer them separated by default though)

**Comment by Steinhagen** [comment] 2016-09-10 18:55
I also consider that nowdock is ready for the 0.3 release.
The sheer number of fixes and improvements done from 0.2.2 is more than enough for a single release.

**Comment by alexjp** [comment] 2016-09-10 18:58
> For instance, is there a reason why nowdock plasmoid is not just inside a nowdock panel by default? 

I myself don't use it with the nowdock panel. I use it on normal panel. Also, if "different launchers per activity" didn't existed, I would use it outside the panel ( which is still not a bad idea, since it works very well that way with animation and transparency ).

**Comment by kupiqu** [comment] 2016-09-10 19:01
Ok, transparency is a thing, until it is (hopefully) fixed in Plasma 5.9. But what is the advantage of a regular panel against nowdock panel?

**Comment by alexjp** [comment] 2016-09-10 19:06
> Ok, transparency is a thing, until it is (hopefully) fixed in Plasma 5.9. But what is the advantage of a regular panel against nowdock panel?

The spacer: I am able to put Kickoff at top, nowdock plasmoid, and then at the bottom the systray. -> see http://imgur.com/adKyfCd

**Comment by kupiqu** [comment] 2016-09-10 19:16
Indeed. I didn't know about the spacer issue.

This would also affect the nowdock panel if it tries to reproduce default
panel in vanilla plasma, which I assume adds the system tray (and would
require a working spacer).

Perhaps it's better to release now as is and postpone default use case for
when transparent and spacer issues are solved...

**Comment by psifidotos** [comment] 2016-09-10 20:16
Well, please let me add in this conversation the following...

> For instance, is there a reason why nowdock plasmoid is not just inside a nowdock panel by default? 

well, there is... It can not be done from the code of the panel... As I mentioned earlier when a new panel is implemented that creates the  "**Empty** Now Dock Panel" record in panels list... The **Default** Now Dock Panel must be installed in a different way (through **layouts packages**) and the installation is not straight forward the user must use command line to install **layout packages** . I have a layout package in my system for **"Default Now Dock Panel"** if you wanna try it... It adds a Now Dock panel and inside it a Now Dock Plasmoid and an analog clock.

**Now.... The news....**
Well, since the begin of the Now Dock implementation there were some issues that annoied me a lot...
- buffers for the icons were created by timers and this had some rare cases that  **blank** tasks were appearing
- zooming had blurred version of the icon during hovering
- the buffers consumed memory
- the icon sizes where the defaults and this was creating jumps for icon sizes in automatic mode

This whole situation broke my nerves... :) soon enough it was going to need a refactoring because of the above... So what I have done today:
- I managed to use QIconItems instead of PlasmaCore.IconItems. This gives us svg versions for the icons.
- The icons **NEVER** have blurring
- I dropped the buffers and I kept only one for the shadows... This has freed memory
- the implentation is simpler that way
- I made the margins used relevant to the icon size

the cons, 
- during hovering a little more cpu in used because we provide **free blurred** icons always

you can test the above in **svgs** branches of both plasmoid and panel... I need a little more polishing for the automatic mode but it will get there...

**Concerning the 0.3**
_supporting spacers, is tricky... because for example the top items should be animated differently from the bottom ones... I should go for 0.4 for this and probably supporting two spacers, not more, I could try the next week to see how much work this have... So somenone will be able to have 3 different positions for its plasmoids at the same time, e.g. left, center, right_

Please test test test... :) the svg branches the next days... 
For **0.3** I am thinking
- polish everything with the new svg approach
- approach the spacer problem _(for this I am not sure...)_

Window Previews are going to 0.4 the above are fundamentals and more **important** I think...

**Comment by kupiqu** [comment] 2016-09-10 20:39
It sounds great. I Will test tonight.

I hope 0.4 comes soon after 0.3... ;)

**Comment by SteveKej** [comment] 2016-09-10 23:59
Ha! late to the party again :D

I'll test the svg branches soon. As Steinhagen mentioned there's been so much work done since 0.2.2.  I feel the time is more than right for another point release.

**Comment by kupiqu** [comment] 2016-09-11 01:40
Just tested it, and it works nicely.

As you said only icons in nowdock-plasmoid respect the proper automatic size while other icons in the nowdock panel appear slightly smaller.

This is not a big deal for me, so I'll keep my nowdock using this branch for now...

**Comment by psifidotos** [comment] 2016-09-11 07:23
> As you said only icons in nowdock-plasmoid respect the proper automatic size while other icons in the nowdock panel appear slightly smaller.

**svgs** is going to be the **master** branches soon enough. I have also enabled a user choice for the icon sizes changes. The user can choose from the Now Dock Panel settings to use "small steps during automatic modes". By default the first behavior is enabled that keeps also the viusals correct... :) let the user decide what they preffer with the current plasma's limitations... :)

**update:** concerning windows previews and spacer issue for Now Dock panel. I have the oppinion that I will go for **Windows Previes in 0.3** and for **spacers in 0.4** _(but I will not promise that, spacers in Now Dock Panel could be supported but they would make the code much complex and difficult to maintain after that, the easiest solution would be only one spacer and such two places in the panel for your plasmoids... e.g. left and right. The supported places would be,  left, center, right and left+right)_

**Comment by kupiqu** [comment] 2016-09-11 18:46
Somehow this last change broke the automatic scale of icons in my system and now icons appear all very small compared to the width of the panel.

Any idea of what may be going on?

**Comment by psifidotos** [comment] 2016-09-11 19:13
are you using latest [svgs] branches for both?

what are the Now Dock Panel settings? icon size, zoom, small steps
and maybe a screenhost showing how big is your panel in width and height...

**Comment by kupiqu** [comment] 2016-09-11 19:29
I think the problem happened when I pulled new commits for the plasmoid and switched to its "svgs" branch.

If "small steps for icon sizes in automatic mode" is unselected, then the behavior is like I described above.

<img width="69" alt="screenshot_20160911_152722" src="https://cloud.githubusercontent.com/assets/3875196/18419926/699d4a1a-7834-11e6-991c-42da63ed09a5.png">

If I enable that option, then it comes back to normal (although at first only while the desktop shell was unlocked, but somehow I could fix it, so it now remains the same).

<img width="70" alt="screenshot_20160911_152647" src="https://cloud.githubusercontent.com/assets/3875196/18419927/6f50fdb2-7834-11e6-814a-027201b4f699.png">

My settings are: icon size (automatic), zoom (1.25)

**Comment by psifidotos** [comment] 2016-09-11 19:41
if you have **unselected** "small steps" then icon sizes can be only of the default values,
16,24,32,48,64,92,128,256 **nothing in between this values**
I dont see I think any unexpected behavior.. If you close plasma
kquitapp plasmashell
kstart plasmashell

there are some debugging messages that show which icon size is set each time...

**Comment by psifidotos** [comment] 2016-09-11 19:42
with **selected "small steps"** the icon size can be a modular of 8 so...
_...32,40,48,56,64.... etc...._

**Comment by psifidotos** [comment] 2016-09-11 22:02
I have added initial support for **window previews** in **[svgs]** branch for the plasmoid. It can be enabled through the configuration window...

**Comment by Steinhagen** [comment] 2016-09-11 22:20
> 16,24,32,48,64,**92**,128,256 nothing in between this values

Should be 96 instead of 92.

**Comment by alexjp** [comment] 2016-09-11 22:51
> I have added initial support for window previews in [svgs] branch for the plasmoid. It can be enabled through the configuration window...

Seems very good :)

**Comment by psifidotos** [comment] 2016-09-11 23:11
;)

**Comment by alexjp** [comment] 2016-09-14 07:15
I think you can ship the current master.

The config dialog redesign was very nice, well done. I think nowdock is in great shape ! I won't go back into the default taskmanager anytime soon.

**Comment by psifidotos** [comment] 2016-09-15 17:39
eveything in **master** branches for panel and plasmoid and small fixes ... Last days before **0.3** release... :-)

**Comment by alexjp** [comment] 2016-09-15 18:27
@psifidotos Go for it :) When you are rich and famous, remember us !

Last few days, didn't find any issue.

**Comment by psifidotos** [comment] 2016-09-15 18:56
@alexjp thank u!!! I just hope that Now Dock will help the plasma users... :)!!

**Comment by psifidotos** [comment] 2016-09-15 18:59
I have just thought that I need to update the names everywhere from **org.kdelook.nowdock** to **org.kde.store** this is going to not keep previous configurations from Now Dock 0.2.2  but sooner or later it should be done...

**Comment by alexjp** [comment] 2016-09-15 20:07
Hope i catch you in time before release:

Plasma 5.8 is near release ( testing beta on gentoo right now ). There is a line of code ( the screen on main.qml ) that makes it not work on plasma 5.8:
`screen: plasmoid.screen`
must be removed.

**Comment by Steinhagen** [comment] 2016-09-15 20:14
I can also confirm this behaviour with the latest 5.8 release:
_org.kdelook.nowdock/contents/ui/main.qml:205:9_

```
screen: plasmoid.screen
```

**Comment by psifidotos** [comment] 2016-09-15 21:53
this will disable probably per screen filtering... either way I will comment it in order to be complient with both Plasma 5.7, 5.8... when Plasma 5.8.2 and later arrives  I will backport the new way of filtering per screen...

**Comment by psifidotos** [comment] 2016-09-15 22:06
**BE CAREFUL!!!! I have just updated _[master]_ branches in order to support Plasma 5.8 and I have also updated the plasmoids and panels names!!! This means that before using these versions you should first uninstall totally older versions of the Now Dock Plasmoid and Panel!!!**

**Comment by psifidotos** [comment] 2016-09-15 22:11
**I think that the 0.3 launch could be this Sunday, if anything else does not arise... So please lets make a last check in master branches....**

**Comment by psifidotos** [comment] 2016-09-18 09:06
Thank u all !!!!! :)

https://psifidotos.blogspot.gr/2016/09/now-dock-panel-plasmoid-v03-is-here.html#more

**Comment by psifidotos** [comment] 2016-09-18 10:39
A great thank u for every participation in the project!!!!! :)

**Closed as completed** 2016-09-20 12:19 UTC
Labels: question, Community
